<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\LOGO2.jpeg" />
    <None Remove="images\quiz.png" />
    <None Remove="VoiceGreeting.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="VoiceGreeting.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="4.0.2" />
    <PackageReference Include="Microsoft.ML.DataView" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\LOGO2.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\quiz.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\pinky.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
